enum FastStoreBlocEventType {
  init,
  initialized,
  loadProducts,
  productsLoaded,
  loadProductsFailed,
  purchaseProduct,
  productPurchased,
  purchaseProductFailed,
  purchaseProducCanceled,
  restorePurchases,
  purchasesRestored,
  purchaseRestored,
  restorePurchasesFailed,
}
